# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/CMakeModules/AddZstdCompilationFlags.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/CMakeModules/GetZstdLibraryVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/CMakeModules/JoinPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/CMakeModules/ZstdBuild.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/CMakeModules/ZstdDependencies.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/CMakeModules/ZstdOptions.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/CMakeModules/ZstdPackage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/CMakeModules/ZstdVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/lib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/lib/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/programs/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/build/cmake/zstdConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/zstd/lib/libzstd.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeCheckCompilerFlagCommonPatterns.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckCCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckCXXCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckLinkerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckFlagCommonConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckLinkerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/opt/homebrew/bin/cmake -P /Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios/CMakeFiles/VerifyGlobs.cmake

/Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/klambert/workspace_KJSL/github_kevleyski/surge -B/Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios
