# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/sst/sst-effects/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/libs/sst/sst-effects/cmake/CmakeRC.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeParseArguments.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/opt/homebrew/bin/cmake -P /Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios/CMakeFiles/VerifyGlobs.cmake

/Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/klambert/workspace_KJSL/github_kevleyski/surge -B/Users/klambert/workspace_KJSL/github_kevleyski/surge/build_ios
